["as const satisfies"]
prefix = "acs"
body = "as const satisfies $0"
description = "as const satisfies"

["import"]
prefix = "imp"
body = "import { $0 } from '$1';"
description = "import"

["import all"]
prefix = "ima"
body = "import * as ${0:M} from '$1';"
description = "import all"

["import jsr"]
prefix = "imj"
body = "import * as ${0:M} from 'jsr:$1';"
description = "import jsr"
